## Release name format
name-template: '🚀 Release $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

## Release body template (This is required)
template: |
  ## What's Changed
  $CHANGES

## ##Categories for grouping changes
categories:
  - title: '✨ Features'
    labels:
      - feature
      - enhancement

  - title: '🐛 Bug Fixes'
    labels:
      - fix
      - bug

  - title: '🛠 Maintenance'
    labels:
      - chore
      - refactor

version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - feature
  patch:
    labels:
      - bug
      - fix
  default: patch

# Optional: Labels to exclude from changelog
exclude-labels:
  - ignore
  - skip-changelog

# Change entry template
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
