name-template: '🚀 Release v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
change-template: '- $TITLE (#$NUMBER)'
categories:
  - title: '✨ Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - bug
      - fix
  - title: '🛠 Maintenance'
    labels:
      - chore
      - refactor

exclude-labels:
  - ignore
version-resolver:
  minor:
    labels:
      - feature
  patch:
    labels:
      - fix
  default: patch
